Algoritmo "Doação"

Var

doacao: real

Inicio

escreval("-------------------------------")
escreval("    CAMPANHA DE ARRECADAÇÃO    ")
escreval("-------------------------------")
escreval("")
escreval(" Muito obrigada por ajudar   ")
escreval("")
escreval("  [1] para doar R$ 10.00")
escreval("  [2] para doar R$ 25.00")
escreval("  [3] para doar R$ 50.00")
escreval("  [4] para doar outros valores")
escreval("  [5] para cancelar")
Fimalgoritmo